package labs.client.windows;

import labs.commands.Executable;
import labs.util.ArgumentProvider;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class TableWindow extends JFrame {
    private JTable table1;
    private JPanel panel1;
    private JButton perform_actionButton;
    private JComboBox comboBox1;
    private ArgumentProvider<String> provider;
    private Executable add;
    private Executable history;
    private Executable delete;

    public JTable initTable(String[][] data) {
        String[] columnNames = {"NAME", "TIME", "DISTANCE", "XCOORDINATES", "YCOORDINATES", "LOCATIONNAME", "XLOCCOOR,",
                "YLOCCOOR"};
        String[][] tableData = {{" ", " ", " ", " ", " ", " ", " ", " "}};
        if (data.length > 0)
            tableData = data;
        return new JTable(tableData, columnNames);
    }

    public void setup(ArgumentProvider<String> provider, Executable add, Executable history, Executable delete) {
        String[][] tableData = {{" ", " ", " ", " ", " ", " ", " ", " "}};
        table1 = initTable(tableData);
        perform_actionButton.addActionListener(e -> {
            switch (comboBox1.getSelectedIndex()) {
                case 0:
                    SwingUtilities.invokeLater(() -> new RouteAddWindow(provider, add));
                    break;
                case 1:
                    history.execute();
                    break;
                case 2:
                    SwingUtilities.invokeLater(() -> new DeleteIdWindow(delete, provider));
                    break;
                case 3:
                    SwingUtilities.invokeLater(LanguagePicker::new);
                    break;
            }
        });
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        this.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        perform_actionButton = new JButton();
        perform_actionButton.setText("Perform_action");
        panel1.add(perform_actionButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(323, 30), null, 0, false));
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("add_element");
        defaultComboBoxModel1.addElement("history");
        defaultComboBoxModel1.addElement("delete_by_id");
        defaultComboBoxModel1.addElement("switch_language");
        comboBox1.setModel(defaultComboBoxModel1);
        panel1.add(comboBox1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        table1 = new JTable();
        table1.putClientProperty("Table.isFileList", Boolean.FALSE);
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
